---

- name: Import install_debian.yml if OS family is Debian
  import_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Import install_redhat.yml if OS family is RedHat
  import_tasks: install_redhat.yml
  when: ansible_os_family == "RedHat"
